# Generated by Django 4.0.2 on 2022-02-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dot',
            name='xcoord',
            field=models.CharField(max_length=80, verbose_name='Координата Х'),
        ),
        migrations.AlterField(
            model_name='dot',
            name='ycoord',
            field=models.CharField(max_length=80, verbose_name='Координата У'),
        ),
    ]
